### ISSUE TITLE
not working in production

### ISSUE THREAD

**Issue by pindjur** [KyleAMathews/gatsby-plugin-vanilla-extract#10]
In production ,there is a mismatch between classes in style element and those applied to component dom nodes. It seems that those in style element are minified while second are not.

### Steps to reporoduce 
1. clone https://github.com/pindjur/gatsby-starter-default-vanilla-bug.git
2. run gatsby build and gatsby serve
3. visit http://localhost:9000/

### Expected result
Header styles are applied
### Actual result 
Header styles are not applied

**Comment by KyleAMathews** [comment]
What do the two class names look like?

**Comment by pindjur** [comment]
@KyleAMathews _1lufmvg0 and header_header__1lufmvg0

**Comment by hellomichael** [comment]
@KyleAMathews Just bumping this as I'm having the same issue as well. Thanks for any help.

**Comment by KyleAMathews** [comment]
Can you see the error in dev with DEV_SSR enabled?

**Comment by hellomichael** [comment]
With the DEV_SSR flag enabled, dev is working as expected.

**Comment by KyleAMathews** [comment]
I'm not sure how to help. Could you raise an issue in the vanilla extract repo?

**Comment by pindjur** [comment]
This bug is introduced in #1. PR coming up.
